#!/bin/bash

### qsub file.name to run from anywhere

#PBS -N SE_STAR
#PBS -S /bin/bash
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=8
#PBS -l mem=32gb
#PBS -o /gpfs/data/mcnerney-lab/liuweihan/bulk_RNA/Stephanie/Star/star_exe.out
#PBS -e /gpfs/data/mcnerney-lab/liuweihan/bulk_RNA/Stephanie/Star/star_exe.err

date
module load gcc/6.2.0
module load STAR/2.6.1d

cd /gpfs/data/mcnerney-lab/liuweihan/bulk_RNA/Stephanie/Fastq

for i in $(ls *.fastq.gz)
do
echo $i
sample_prefix=`echo $i | awk -F "L005" '{print $1}'`
echo $sample_prefix


STAR --runThreadN 8 \
--genomeDir /gpfs/data/mcnerney-lab/liuweihan/CUX1_CASP_diff_ref_transcriptome_bulk/mm10_ref$
--readFilesIn $i \
--readFilesCommand zcat \
--outFileNamePrefix $sample_prefix \
--outSAMtype BAM SortedByCoordinate

done

date
echo






